# see https://github.com/viamrobotics/build-action for help
name: Build and Publish RC

on:
  release:
    types: [published]

# To test workflow updates you need to work in a branch directly on viam-modules/bosch
# and tag your working branch instead of @main in any viam-modules/bosch "uses" below.
# Don't forget to tag back to @main before merge.

jobs:
  test:
    uses: ./.github/workflows/test.yml

  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: viamrobotics/build-action@v1
        with:
          # note: you can replace this line with 'version: ""' if
          # you want to test the build process without deploying
          version: ${{ github.ref_name }}
          ref: ${{ github.sha }}
          key-id: ${{ secrets.VIAM_DEV_API_KEY_ID }}
          key-value: ${{ secrets.VIAM_DEV_API_KEY }}
