name: Build and Publish RC

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+'

jobs:
  test:
    uses: ./.github/workflows/test.yml

name: Build and Publish Stable

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

# To test workflow updates you need to work in a branch directly on viamrobotics/viam-cartographer
# and tag your working branch instead of @main in any viamrobotics/viam-cartographer "uses" below.
# Don't forget to tag back to @main before merge.

jobs:
  test:
    uses: ./.github/workflows/test.yml

  slack-workflow-status:
    if: ${{ failure() }}
    name: Post Workflow Status To Slack
    needs:
      - test
    runs-on: ubuntu-latest
    permissions:
      actions: 'read'

name: Build & Publish Module to Registry

on:
  release:
    types: [published]

jobs:
  publish:
    strategy:
      matrix:
        include:
          - platform: linux/amd64
            runner: ubuntu-latest
            target_os: linux
            target_arch: amd64
          - platform: linux/arm64
            runner: buildjet-8vcpu-ubuntu-2204-arm
            target_os: linux
            target_arch: arm64

    runs-on: ${{ matrix.runner }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21.13

    - name: Install canon
      run: |
        export PATH="$(go env GOPATH)/bin:$PATH"
        go install github.com/viamrobotics/canon@v1.0.0

    - name: Build and package
      run: |
        canon --profile bosch
        TARGET_OS=${{ matrix.target_os }} TARGET_ARCH=${{ matrix.target_arch }} make module

    - name: Upload bosch module to registry
      uses: viamrobotics/upload-module@main
      with:
        meta-path: meta.json
        module-path: module.tar.gz
        platform: ${{ matrix.platform }}
        version: ${{ github.ref_name }}
        key-id: ${{ secrets.VIAM_DEV_API_KEY_ID }}
        key-value: ${{ secrets.VIAM_DEV_API_KEY }}